Generate Compara files and document script executed on SLURM
Ensembl/nf-sql-to-parquet pull request #5
Opened 2024-07-25 14:30 UTC by sudenni

- added Compara schema, JSON and SQL with config parameters for compara URI and version
- more memory for SqlToParquet process because of out of memory error with compara
- dynamic schema calling to create Parquet files
- added pipeline help message
- updated documentation with actual script used on SLURM

2024-07-25 14:36 UTC, andrewyatz requested changes
Looks good. One change requested about internal params

2024-07-25 14:36 UTC, andrewyatz commented on nextflow/nextflow.config
These files are going to go public so it would be best not to leak internal machine names externally.

2024-07-25 14:50 UTC, sudenni commented on nextflow/nextflow.config
I modified the config, is that what you meant?

2024-07-26 09:00 UTC, andrewyatz approved these changes

2024-07-26 09:01 UTC, merged